#!/bin/bash -e
#
# Run the GA4GH CTK
#
# When this script runs it will move aside any existing target/ (with your
# previous test results) into a directory named target-`date -Iseconds`
#
# This script passes in the most important properties to control
# the CTK, but you can also control the CTK using the application.properties
# and log4j2.xml files, or by simply setting the controlling properties in
# your general environment.
#
###############################################################################
set -e          # exit on command errors (so you MUST handle exit codes properly!)
set -E          # pass trap handlers down to subshells
set -o pipefail # capture fail exit codes in piped commands
#set -x         # execution tracing debug messages

# Error handler
on_err() {
	echo ">> ERROR: $?"
	FN=0
	for LN in "${BASH_LINENO[@]}"; do
		[ "${FUNCNAME[$FN]}" = "main" ] && break
		echo ">> ${BASH_SOURCE[$FN]} $LN ${FUNCNAME[$FN]}"
		FN=$(( FN + 1 ))
	done
}
trap on_err ERR

# Exit handler
declare -a EXIT_CMDS
add_exit_cmd() { EXIT_CMDS+="$*;  "; }
on_exit(){ eval "${EXIT_CMDS[@]}"; }
trap on_exit EXIT

# Get command info
CMD_PWD=$(pwd)
CMD="$0"
CMD_DIR="$(cd "$(dirname "$CMD")" && pwd -P)"

# Defaults and command line options
[ "$VERBOSE" ] ||  VERBOSE=
[ "$DEBUG" ]   ||  DEBUG=
[ "$CTKJAR" ]  ||  CTKJAR="ctk-testpack-0.5.1-SNAPSHOT.jar"
[ "$ctk_tgt_urlRoot" ] || ctk_tgt_urlRoot="http://localhost:8000/v0.5.1/"
[ "$ctk_matchstr" ] || ctg_matchstr=".*IT.*"
[ "$TGTDIR" ] || TGTDIR="target"


# Basic helpers
out() { echo "$(date +%Y%m%dT%H%M%SZ): $*"; }
err() { out "$*" 1>&2; }
vrb() { [ ! "$VERBOSE" ] || out "$@"; }
dbg() { [ ! "$DEBUG" ] || err "$@"; }
die() { err "EXIT: $1" && [ "$2" ] && [ "$2" -ge 0 ] && exit "$2" || exit 1; }

# Show help function to be used below
show_help() {
	awk 'NR>1{print} /^(###|$)/{exit}' "$CMD"
	echo "USAGE: $(basename "$CMD") [arguments]"
	echo "ARGS:"
	MSG=$(awk '/^NARGS=-1; while/,/^esac; done/' "$CMD" | sed -e 's/^[[:space:]]*/  /' -e 's/|/, /' -e 's/)//' | grep '^  -')
	EMSG=$(eval "echo \"$MSG\"")
	echo "$EMSG"
}

# Parse command line options (odd formatting to simplify show_help() above)
NARGS=-1; while [ "$#" -ne "$NARGS" ]; do NARGS=$#; case $1 in
	# SWITCHES
	-h|--help)      # This help message
		show_help; exit 1; ;;
	-d|--debug)     # Enable debugging messages (implies verbose)
		DEBUG=$(( DEBUG + 1 )) && VERBOSE="$DEBUG" && shift && echo "#-INFO: DEBUG=$DEBUG (implies VERBOSE=$VERBOSE)"; ;;
	-v|--verbose)   # Enable verbose messages
		VERBOSE=$(( VERBOSE + 1 )) && shift && echo "#-INFO: VERBOSE=$VERBOSE"; ;;
	# PAIRS
	-m|--ctk_matchstr)     # Set the matchstring to a value (DEFAULT: $ctk_matchstr)
		shift && ctk_matchstr="$1" && shift && vrb "#-INFO: ctk_matchstr=$ctk_matchstr"; ;;
	-u|--ctk_tgt_urlRoot)  # Set the urlRoot to a value (DEFAULT: $ctk_tgt_urlRoot)
		shift && ctk_tgt_urlRoot="$1" && shift && vrb "#-INFO: ctk_tgt_urlRoot=$ctk_tgt_urlRoot"; ;;
	*)
		break;
esac; done

[ "$DEBUG" ]  &&  set -x

###############################################################################

# Validate some things
[ $# -gt 0 -a -z "$ctk.tgt.urlRoot" ]  &&  ctk_tgt_urlRoot="$1"  &&  shift
# [ "$ctk_matchstr" ]  ||  die "You must provide a test-selecting match string (ctk_matchstr)!"
# [ "$ctk_tgt_urlRoot" ]  ||  die "You must provide a target server (ctk_tgt_urlRoot)!"
[ $# -eq 0 ]  ||  die "ERROR: Unexpected commands!"

# if target/ exists, amend its name
if [ -d "$TGTDIR" ]; then
  NEWDIR=${TGTDIR}-`date -Iseconds`
  mv ${TGTDIR} $NEWDIR
  # if the just-renamed directory is empty, we can forget it
  if [ "$(ls -A $NEWDIR)" ]; then
        out "moved existing results to "${NEWDIR}
  else
      rmdir $NEWDIR
  fi
fi
# if no target/ then create it
mkdir ${TGTDIR}

# run the CTK
# other properties are set in application.properties, log4j2.xml
# Probably should use full-blown JAVACMD var to find/use specific JDK, props etc
java -Dctk.matchstr=$ctk_matchstr -Dctk.tgt.urlRoot=$ctk_tgt_urlRoot -jar ${CTKJAR}