package org.ga4gh;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link GAMetadata} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAMetadataAssert extends AbstractAssert<GAMetadataAssert, GAMetadata> {

  /**
   * Creates a new <code>{@link GAMetadataAssert}</code> to make assertions on actual GAMetadata.
   * @param actual the GAMetadata we want to make assertions on.
   */
  public GAMetadataAssert(GAMetadata actual) {
    super(actual, GAMetadataAssert.class);
  }

  /**
   * An entry point for GAMetadataAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAMetadata)</code> and get specific assertion with code completion.
   * @param actual the GAMetadata we want to make assertions on.
   * @return a new <code>{@link GAMetadataAssert}</code>
   */
  public static GAMetadataAssert assertThat(GAMetadata actual) {
    return new GAMetadataAssert(actual);
  }

}
