package org.ga4gh;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link GASearchAnalysesRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchAnalysesRequestAssert extends AbstractAssert<GASearchAnalysesRequestAssert, GASearchAnalysesRequest> {

  /**
   * Creates a new <code>{@link GASearchAnalysesRequestAssert}</code> to make assertions on actual GASearchAnalysesRequest.
   * @param actual the GASearchAnalysesRequest we want to make assertions on.
   */
  public GASearchAnalysesRequestAssert(GASearchAnalysesRequest actual) {
    super(actual, GASearchAnalysesRequestAssert.class);
  }

  /**
   * An entry point for GASearchAnalysesRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchAnalysesRequest)</code> and get specific assertion with code completion.
   * @param actual the GASearchAnalysesRequest we want to make assertions on.
   * @return a new <code>{@link GASearchAnalysesRequestAssert}</code>
   */
  public static GASearchAnalysesRequestAssert assertThat(GASearchAnalysesRequest actual) {
    return new GASearchAnalysesRequestAssert(actual);
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchAnalysesRequest's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest's classSchema is not equal to the given one.
   */
  public GASearchAnalysesRequestAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchAnalysesRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest's name is equal to the given one.
   * @param name the given name to compare the actual GASearchAnalysesRequest's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest's name is not equal to the given one.
   */
  public GASearchAnalysesRequestAssert hasName(String name) {
    // check that actual GASearchAnalysesRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchAnalysesRequest's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest's pageSize is not equal to the given one.
   */
  public GASearchAnalysesRequestAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchAnalysesRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchAnalysesRequest's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest's pageToken is not equal to the given one.
   */
  public GASearchAnalysesRequestAssert hasPageToken(String pageToken) {
    // check that actual GASearchAnalysesRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchAnalysesRequest's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest's schema is not equal to the given one.
   */
  public GASearchAnalysesRequestAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchAnalysesRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }




}
