package org.ga4gh;

/**
 * {@link GAMetadata.Callback} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAMetadataCallbackAssert extends AbstractAssert<GAMetadataCallbackAssert, GAMetadata.Callback> {

  /**
   * Creates a new <code>{@link GAMetadataCallbackAssert}</code> to make assertions on actual GAMetadata.Callback.
   * @param actual the GAMetadata.Callback we want to make assertions on.
   */
  public GAMetadataCallbackAssert(GAMetadata.Callback actual) {
    super(actual, GAMetadataCallbackAssert.class);
  }

  /**
   * An entry point for GAMetadataCallbackAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAMetadata.Callback)</code> and get specific assertion with code completion.
   * @param actual the GAMetadata.Callback we want to make assertions on.
   * @return a new <code>{@link GAMetadataCallbackAssert}</code>
   */
  public static GAMetadataCallbackAssert assertThat(GAMetadata.Callback actual) {
    return new GAMetadataCallbackAssert(actual);
  }

}
