package org.ga4gh;

import org.assertj.core.api.*;

/**
 * {@link GAMetadataMethods} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAMetadataMethodsAssert extends AbstractAssert<GAMetadataMethodsAssert, GAMetadataMethods> {

  /**
   * Creates a new <code>{@link GAMetadataMethodsAssert}</code> to make assertions on actual GAMetadataMethods.
   * @param actual the GAMetadataMethods we want to make assertions on.
   */
  public GAMetadataMethodsAssert(GAMetadataMethods actual) {
    super(actual, GAMetadataMethodsAssert.class);
  }

  /**
   * An entry point for GAMetadataMethodsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAMetadataMethods)</code> and get specific assertion with code completion.
   * @param actual the GAMetadataMethods we want to make assertions on.
   * @return a new <code>{@link GAMetadataMethodsAssert}</code>
   */
  public static GAMetadataMethodsAssert assertThat(GAMetadataMethods actual) {
    return new GAMetadataMethodsAssert(actual);
  }

}
