package org.ga4gh;

/**
 * {@link GAMetadataMethods.Callback} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAMetadataMethodsCallbackAssert extends AbstractAssert<GAMetadataMethodsCallbackAssert, GAMetadataMethods.Callback> {

  /**
   * Creates a new <code>{@link GAMetadataMethodsCallbackAssert}</code> to make assertions on actual GAMetadataMethods.Callback.
   * @param actual the GAMetadataMethods.Callback we want to make assertions on.
   */
  public GAMetadataMethodsCallbackAssert(GAMetadataMethods.Callback actual) {
    super(actual, GAMetadataMethodsCallbackAssert.class);
  }

  /**
   * An entry point for GAMetadataMethodsCallbackAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAMetadataMethods.Callback)</code> and get specific assertion with code completion.
   * @param actual the GAMetadataMethods.Callback we want to make assertions on.
   * @return a new <code>{@link GAMetadataMethodsCallbackAssert}</code>
   */
  public static GAMetadataMethodsCallbackAssert assertThat(GAMetadataMethods.Callback actual) {
    return new GAMetadataMethodsCallbackAssert(actual);
  }

}
