package org.ga4gh;

import org.assertj.core.api.*;
import org.assertj.core.internal.*;
import org.assertj.core.util.*;

/**
 * {@link GASearchIndividualsRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchIndividualsRequestAssert extends AbstractAssert<GASearchIndividualsRequestAssert, GASearchIndividualsRequest> {

  /**
   * Creates a new <code>{@link GASearchIndividualsRequestAssert}</code> to make assertions on actual GASearchIndividualsRequest.
   * @param actual the GASearchIndividualsRequest we want to make assertions on.
   */
  public GASearchIndividualsRequestAssert(GASearchIndividualsRequest actual) {
    super(actual, GASearchIndividualsRequestAssert.class);
  }

  /**
   * An entry point for GASearchIndividualsRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchIndividualsRequest)</code> and get specific assertion with code completion.
   * @param actual the GASearchIndividualsRequest we want to make assertions on.
   * @return a new <code>{@link GASearchIndividualsRequestAssert}</code>
   */
  public static GASearchIndividualsRequestAssert assertThat(GASearchIndividualsRequest actual) {
    return new GASearchIndividualsRequestAssert(actual);
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchIndividualsRequest's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest's classSchema is not equal to the given one.
   */
  public GASearchIndividualsRequestAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest's groupIds contains the given String elements.
   * @param groupIds the given elements that should be contained in actual GASearchIndividualsRequest's groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest's groupIds does not contain all given String elements.
   */
  public GASearchIndividualsRequestAssert hasGroupIds(String... groupIds) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (groupIds == null) failWithMessage("Expecting groupIds parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getGroupIds(), groupIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest's groupIds contains <b>only<b> the given String elements and nothing else in whatever order.
   * @param groupIds the given elements that should be contained in actual GASearchIndividualsRequest's groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest's groupIds does not contain all given String elements.
   */
  public GASearchIndividualsRequestAssert hasOnlyGroupIds(String... groupIds) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (groupIds == null) failWithMessage("Expecting groupIds parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getGroupIds(), groupIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest's groupIds does not contain the given String elements.
   *
   * @param groupIds the given elements that should not be in actual GASearchIndividualsRequest's groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest's groupIds contains any given String elements.
   */
  public GASearchIndividualsRequestAssert doesNotHaveGroupIds(String... groupIds) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (groupIds == null) failWithMessage("Expecting groupIds parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getGroupIds(), groupIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest has no groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest's groupIds is not empty.
   */
  public GASearchIndividualsRequestAssert hasNoGroupIds() {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have groupIds but had :\n  <%s>";
    
    // check
    if (actual.getGroupIds().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getGroupIds());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchIndividualsRequest's name is equal to the given one.
   * @param name the given name to compare the actual GASearchIndividualsRequest's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest's name is not equal to the given one.
   */
  public GASearchIndividualsRequestAssert hasName(String name) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchIndividualsRequest's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest's pageSize is not equal to the given one.
   */
  public GASearchIndividualsRequestAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchIndividualsRequest's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest's pageToken is not equal to the given one.
   */
  public GASearchIndividualsRequestAssert hasPageToken(String pageToken) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchIndividualsRequest's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest's schema is not equal to the given one.
   */
  public GASearchIndividualsRequestAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchIndividualsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }





}
