package org.ga4gh;

/**
 * {@link GASearchAnalysesResponse.Builder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchAnalysesResponseBuilderAssert extends AbstractAssert<GASearchAnalysesResponseBuilderAssert, GASearchAnalysesResponse.Builder> {

  /**
   * Creates a new <code>{@link GASearchAnalysesResponseBuilderAssert}</code> to make assertions on actual GASearchAnalysesResponse.Builder.
   * @param actual the GASearchAnalysesResponse.Builder we want to make assertions on.
   */
  public GASearchAnalysesResponseBuilderAssert(GASearchAnalysesResponse.Builder actual) {
    super(actual, GASearchAnalysesResponseBuilderAssert.class);
  }

  /**
   * An entry point for GASearchAnalysesResponseBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchAnalysesResponse.Builder)</code> and get specific assertion with code completion.
   * @param actual the GASearchAnalysesResponse.Builder we want to make assertions on.
   * @return a new <code>{@link GASearchAnalysesResponseBuilderAssert}</code>
   */
  public static GASearchAnalysesResponseBuilderAssert assertThat(GASearchAnalysesResponse.Builder actual) {
    return new GASearchAnalysesResponseBuilderAssert(actual);
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder's analyses contains the given GAAnalysis elements.
   * @param analyses the given elements that should be contained in actual GASearchAnalysesResponse.Builder's analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse.Builder's analyses does not contain all given GAAnalysis elements.
   */
  public GASearchAnalysesResponseBuilderAssert hasAnalyses(GAAnalysis... analyses) {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given GAAnalysis varargs is not null.
    if (analyses == null) failWithMessage("Expecting analyses parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getAnalyses(), analyses);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder's analyses contains <b>only<b> the given GAAnalysis elements and nothing else in whatever order.
   * @param analyses the given elements that should be contained in actual GASearchAnalysesResponse.Builder's analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse.Builder's analyses does not contain all given GAAnalysis elements.
   */
  public GASearchAnalysesResponseBuilderAssert hasOnlyAnalyses(GAAnalysis... analyses) {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given GAAnalysis varargs is not null.
    if (analyses == null) failWithMessage("Expecting analyses parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getAnalyses(), analyses);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder's analyses does not contain the given GAAnalysis elements.
   *
   * @param analyses the given elements that should not be in actual GASearchAnalysesResponse.Builder's analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse.Builder's analyses contains any given GAAnalysis elements.
   */
  public GASearchAnalysesResponseBuilderAssert doesNotHaveAnalyses(GAAnalysis... analyses) {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given GAAnalysis varargs is not null.
    if (analyses == null) failWithMessage("Expecting analyses parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getAnalyses(), analyses);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder has no analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse.Builder's analyses is not empty.
   */
  public GASearchAnalysesResponseBuilderAssert hasNoAnalyses() {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have analyses but had :\n  <%s>";
    
    // check
    if (actual.getAnalyses().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getAnalyses());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder's nextPageToken is equal to the given one.
   * @param nextPageToken the given nextPageToken to compare the actual GASearchAnalysesResponse.Builder's nextPageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse.Builder's nextPageToken is not equal to the given one.
   */
  public GASearchAnalysesResponseBuilderAssert hasNextPageToken(String nextPageToken) {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nextPageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualNextPageToken = actual.getNextPageToken();
    if (!Objects.areEqual(actualNextPageToken, nextPageToken)) {
      failWithMessage(assertjErrorMessage, actual, nextPageToken, actualNextPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder has analyses.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse.Builder does not have analyses.
   */
  public GASearchAnalysesResponseBuilderAssert hasAnalyses() {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasAnalyses()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesResponse.Builder has analyses but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder does not have analyses.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse.Builder has analyses.
   */
  public GASearchAnalysesResponseBuilderAssert doesNotHaveAnalyses() {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasAnalyses()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesResponse.Builder does not have analyses but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder has next page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse.Builder does not have next page token.
   */
  public GASearchAnalysesResponseBuilderAssert hasNextPageToken() {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasNextPageToken()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesResponse.Builder has next page token but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse.Builder does not have next page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse.Builder has next page token.
   */
  public GASearchAnalysesResponseBuilderAssert doesNotHaveNextPageToken() {
    // check that actual GASearchAnalysesResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasNextPageToken()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesResponse.Builder does not have next page token but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

}
