package org.ga4gh;

/**
 * {@link GASearchSamplesRequest.Builder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchSamplesRequestBuilderAssert extends AbstractAssert<GASearchSamplesRequestBuilderAssert, GASearchSamplesRequest.Builder> {

  /**
   * Creates a new <code>{@link GASearchSamplesRequestBuilderAssert}</code> to make assertions on actual GASearchSamplesRequest.Builder.
   * @param actual the GASearchSamplesRequest.Builder we want to make assertions on.
   */
  public GASearchSamplesRequestBuilderAssert(GASearchSamplesRequest.Builder actual) {
    super(actual, GASearchSamplesRequestBuilderAssert.class);
  }

  /**
   * An entry point for GASearchSamplesRequestBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchSamplesRequest.Builder)</code> and get specific assertion with code completion.
   * @param actual the GASearchSamplesRequest.Builder we want to make assertions on.
   * @return a new <code>{@link GASearchSamplesRequestBuilderAssert}</code>
   */
  public static GASearchSamplesRequestBuilderAssert assertThat(GASearchSamplesRequest.Builder actual) {
    return new GASearchSamplesRequestBuilderAssert(actual);
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder's individualIds contains the given String elements.
   * @param individualIds the given elements that should be contained in actual GASearchSamplesRequest.Builder's individualIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchSamplesRequest.Builder's individualIds does not contain all given String elements.
   */
  public GASearchSamplesRequestBuilderAssert hasIndividualIds(String... individualIds) {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (individualIds == null) failWithMessage("Expecting individualIds parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getIndividualIds(), individualIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder's individualIds contains <b>only<b> the given String elements and nothing else in whatever order.
   * @param individualIds the given elements that should be contained in actual GASearchSamplesRequest.Builder's individualIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchSamplesRequest.Builder's individualIds does not contain all given String elements.
   */
  public GASearchSamplesRequestBuilderAssert hasOnlyIndividualIds(String... individualIds) {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (individualIds == null) failWithMessage("Expecting individualIds parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getIndividualIds(), individualIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder's individualIds does not contain the given String elements.
   *
   * @param individualIds the given elements that should not be in actual GASearchSamplesRequest.Builder's individualIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchSamplesRequest.Builder's individualIds contains any given String elements.
   */
  public GASearchSamplesRequestBuilderAssert doesNotHaveIndividualIds(String... individualIds) {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (individualIds == null) failWithMessage("Expecting individualIds parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getIndividualIds(), individualIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder has no individualIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchSamplesRequest.Builder's individualIds is not empty.
   */
  public GASearchSamplesRequestBuilderAssert hasNoIndividualIds() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have individualIds but had :\n  <%s>";
    
    // check
    if (actual.getIndividualIds().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getIndividualIds());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder's name is equal to the given one.
   * @param name the given name to compare the actual GASearchSamplesRequest.Builder's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder's name is not equal to the given one.
   */
  public GASearchSamplesRequestBuilderAssert hasName(String name) {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchSamplesRequest.Builder's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder's pageSize is not equal to the given one.
   */
  public GASearchSamplesRequestBuilderAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchSamplesRequest.Builder's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder's pageToken is not equal to the given one.
   */
  public GASearchSamplesRequestBuilderAssert hasPageToken(String pageToken) {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder has individual ids.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder does not have individual ids.
   */
  public GASearchSamplesRequestBuilderAssert hasIndividualIds() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasIndividualIds()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder has individual ids but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder does not have individual ids.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder has individual ids.
   */
  public GASearchSamplesRequestBuilderAssert doesNotHaveIndividualIds() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasIndividualIds()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder does not have individual ids but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder has name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder does not have name.
   */
  public GASearchSamplesRequestBuilderAssert hasName() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder has name but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder does not have name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder has name.
   */
  public GASearchSamplesRequestBuilderAssert doesNotHaveName() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder does not have name but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder has page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder does not have page size.
   */
  public GASearchSamplesRequestBuilderAssert hasPageSize() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder has page size but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder does not have page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder has page size.
   */
  public GASearchSamplesRequestBuilderAssert doesNotHavePageSize() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder does not have page size but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder has page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder does not have page token.
   */
  public GASearchSamplesRequestBuilderAssert hasPageToken() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder has page token but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchSamplesRequest.Builder does not have page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchSamplesRequest.Builder has page token.
   */
  public GASearchSamplesRequestBuilderAssert doesNotHavePageToken() {
    // check that actual GASearchSamplesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchSamplesRequest.Builder does not have page token but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

}
