package org.ga4gh;

import org.assertj.core.api.*;
import org.assertj.core.util.*;

/**
 * {@link GASex} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASexAssert extends AbstractAssert<GASexAssert, GASex> {

  /**
   * Creates a new <code>{@link GASexAssert}</code> to make assertions on actual GASex.
   * @param actual the GASex we want to make assertions on.
   */
  public GASexAssert(GASex actual) {
    super(actual, GASexAssert.class);
  }

  /**
   * An entry point for GASexAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASex)</code> and get specific assertion with code completion.
   * @param actual the GASex we want to make assertions on.
   * @return a new <code>{@link GASexAssert}</code>
   */
  public static GASexAssert assertThat(GASex actual) {
    return new GASexAssert(actual);
  }

  /**
   * Verifies that the actual GASex's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASex's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASex's classSchema is not equal to the given one.
   */
  public GASexAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASex we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

}
