package org.ga4gh;

import org.assertj.core.api.*;
import org.assertj.core.util.*;

/**
 * {@link GASearchIndividualGroupsRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchIndividualGroupsRequestAssert extends AbstractAssert<GASearchIndividualGroupsRequestAssert, GASearchIndividualGroupsRequest> {

  /**
   * Creates a new <code>{@link GASearchIndividualGroupsRequestAssert}</code> to make assertions on actual GASearchIndividualGroupsRequest.
   * @param actual the GASearchIndividualGroupsRequest we want to make assertions on.
   */
  public GASearchIndividualGroupsRequestAssert(GASearchIndividualGroupsRequest actual) {
    super(actual, GASearchIndividualGroupsRequestAssert.class);
  }

  /**
   * An entry point for GASearchIndividualGroupsRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchIndividualGroupsRequest)</code> and get specific assertion with code completion.
   * @param actual the GASearchIndividualGroupsRequest we want to make assertions on.
   * @return a new <code>{@link GASearchIndividualGroupsRequestAssert}</code>
   */
  public static GASearchIndividualGroupsRequestAssert assertThat(GASearchIndividualGroupsRequest actual) {
    return new GASearchIndividualGroupsRequestAssert(actual);
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsRequest's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchIndividualGroupsRequest's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsRequest's classSchema is not equal to the given one.
   */
  public GASearchIndividualGroupsRequestAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchIndividualGroupsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsRequest's name is equal to the given one.
   * @param name the given name to compare the actual GASearchIndividualGroupsRequest's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsRequest's name is not equal to the given one.
   */
  public GASearchIndividualGroupsRequestAssert hasName(String name) {
    // check that actual GASearchIndividualGroupsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsRequest's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchIndividualGroupsRequest's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsRequest's pageSize is not equal to the given one.
   */
  public GASearchIndividualGroupsRequestAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchIndividualGroupsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsRequest's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchIndividualGroupsRequest's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsRequest's pageToken is not equal to the given one.
   */
  public GASearchIndividualGroupsRequestAssert hasPageToken(String pageToken) {
    // check that actual GASearchIndividualGroupsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsRequest's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchIndividualGroupsRequest's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsRequest's schema is not equal to the given one.
   */
  public GASearchIndividualGroupsRequestAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchIndividualGroupsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }




}
