package org.ga4gh;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * {@link GASearchIndividualGroupsResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchIndividualGroupsResponseAssert extends AbstractAssert<GASearchIndividualGroupsResponseAssert, GASearchIndividualGroupsResponse> {

  /**
   * Creates a new <code>{@link GASearchIndividualGroupsResponseAssert}</code> to make assertions on actual GASearchIndividualGroupsResponse.
   * @param actual the GASearchIndividualGroupsResponse we want to make assertions on.
   */
  public GASearchIndividualGroupsResponseAssert(GASearchIndividualGroupsResponse actual) {
    super(actual, GASearchIndividualGroupsResponseAssert.class);
  }

  /**
   * An entry point for GASearchIndividualGroupsResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchIndividualGroupsResponse)</code> and get specific assertion with code completion.
   * @param actual the GASearchIndividualGroupsResponse we want to make assertions on.
   * @return a new <code>{@link GASearchIndividualGroupsResponseAssert}</code>
   */
  public static GASearchIndividualGroupsResponseAssert assertThat(GASearchIndividualGroupsResponse actual) {
    return new GASearchIndividualGroupsResponseAssert(actual);
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsResponse's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchIndividualGroupsResponse's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsResponse's classSchema is not equal to the given one.
   */
  public GASearchIndividualGroupsResponseAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchIndividualGroupsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsResponse's individualGroups contains the given GAIndividualGroup elements.
   * @param individualGroups the given elements that should be contained in actual GASearchIndividualGroupsResponse's individualGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualGroupsResponse's individualGroups does not contain all given GAIndividualGroup elements.
   */
  public GASearchIndividualGroupsResponseAssert hasIndividualGroups(GAIndividualGroup... individualGroups) {
    // check that actual GASearchIndividualGroupsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAIndividualGroup varargs is not null.
    if (individualGroups == null) failWithMessage("Expecting individualGroups parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getIndividualGroups(), individualGroups);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsResponse's individualGroups contains <b>only<b> the given GAIndividualGroup elements and nothing else in whatever order.
   * @param individualGroups the given elements that should be contained in actual GASearchIndividualGroupsResponse's individualGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualGroupsResponse's individualGroups does not contain all given GAIndividualGroup elements.
   */
  public GASearchIndividualGroupsResponseAssert hasOnlyIndividualGroups(GAIndividualGroup... individualGroups) {
    // check that actual GASearchIndividualGroupsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAIndividualGroup varargs is not null.
    if (individualGroups == null) failWithMessage("Expecting individualGroups parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getIndividualGroups(), individualGroups);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsResponse's individualGroups does not contain the given GAIndividualGroup elements.
   *
   * @param individualGroups the given elements that should not be in actual GASearchIndividualGroupsResponse's individualGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualGroupsResponse's individualGroups contains any given GAIndividualGroup elements.
   */
  public GASearchIndividualGroupsResponseAssert doesNotHaveIndividualGroups(GAIndividualGroup... individualGroups) {
    // check that actual GASearchIndividualGroupsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAIndividualGroup varargs is not null.
    if (individualGroups == null) failWithMessage("Expecting individualGroups parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getIndividualGroups(), individualGroups);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsResponse has no individualGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualGroupsResponse's individualGroups is not empty.
   */
  public GASearchIndividualGroupsResponseAssert hasNoIndividualGroups() {
    // check that actual GASearchIndividualGroupsResponse we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have individualGroups but had :\n  <%s>";
    
    // check
    if (actual.getIndividualGroups().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getIndividualGroups());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchIndividualGroupsResponse's nextPageToken is equal to the given one.
   * @param nextPageToken the given nextPageToken to compare the actual GASearchIndividualGroupsResponse's nextPageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsResponse's nextPageToken is not equal to the given one.
   */
  public GASearchIndividualGroupsResponseAssert hasNextPageToken(String nextPageToken) {
    // check that actual GASearchIndividualGroupsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nextPageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualNextPageToken = actual.getNextPageToken();
    if (!Objects.areEqual(actualNextPageToken, nextPageToken)) {
      failWithMessage(assertjErrorMessage, actual, nextPageToken, actualNextPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualGroupsResponse's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchIndividualGroupsResponse's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualGroupsResponse's schema is not equal to the given one.
   */
  public GASearchIndividualGroupsResponseAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchIndividualGroupsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }



}
