package org.ga4gh;

/**
 * {@link GASearchIndividualsResponse.Builder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchIndividualsResponseBuilderAssert extends AbstractAssert<GASearchIndividualsResponseBuilderAssert, GASearchIndividualsResponse.Builder> {

  /**
   * Creates a new <code>{@link GASearchIndividualsResponseBuilderAssert}</code> to make assertions on actual GASearchIndividualsResponse.Builder.
   * @param actual the GASearchIndividualsResponse.Builder we want to make assertions on.
   */
  public GASearchIndividualsResponseBuilderAssert(GASearchIndividualsResponse.Builder actual) {
    super(actual, GASearchIndividualsResponseBuilderAssert.class);
  }

  /**
   * An entry point for GASearchIndividualsResponseBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchIndividualsResponse.Builder)</code> and get specific assertion with code completion.
   * @param actual the GASearchIndividualsResponse.Builder we want to make assertions on.
   * @return a new <code>{@link GASearchIndividualsResponseBuilderAssert}</code>
   */
  public static GASearchIndividualsResponseBuilderAssert assertThat(GASearchIndividualsResponse.Builder actual) {
    return new GASearchIndividualsResponseBuilderAssert(actual);
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder's individuals contains the given GAIndividual elements.
   * @param individuals the given elements that should be contained in actual GASearchIndividualsResponse.Builder's individuals.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsResponse.Builder's individuals does not contain all given GAIndividual elements.
   */
  public GASearchIndividualsResponseBuilderAssert hasIndividuals(GAIndividual... individuals) {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given GAIndividual varargs is not null.
    if (individuals == null) failWithMessage("Expecting individuals parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getIndividuals(), individuals);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder's individuals contains <b>only<b> the given GAIndividual elements and nothing else in whatever order.
   * @param individuals the given elements that should be contained in actual GASearchIndividualsResponse.Builder's individuals.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsResponse.Builder's individuals does not contain all given GAIndividual elements.
   */
  public GASearchIndividualsResponseBuilderAssert hasOnlyIndividuals(GAIndividual... individuals) {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given GAIndividual varargs is not null.
    if (individuals == null) failWithMessage("Expecting individuals parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getIndividuals(), individuals);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder's individuals does not contain the given GAIndividual elements.
   *
   * @param individuals the given elements that should not be in actual GASearchIndividualsResponse.Builder's individuals.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsResponse.Builder's individuals contains any given GAIndividual elements.
   */
  public GASearchIndividualsResponseBuilderAssert doesNotHaveIndividuals(GAIndividual... individuals) {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given GAIndividual varargs is not null.
    if (individuals == null) failWithMessage("Expecting individuals parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getIndividuals(), individuals);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder has no individuals.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsResponse.Builder's individuals is not empty.
   */
  public GASearchIndividualsResponseBuilderAssert hasNoIndividuals() {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have individuals but had :\n  <%s>";
    
    // check
    if (actual.getIndividuals().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getIndividuals());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder's nextPageToken is equal to the given one.
   * @param nextPageToken the given nextPageToken to compare the actual GASearchIndividualsResponse.Builder's nextPageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsResponse.Builder's nextPageToken is not equal to the given one.
   */
  public GASearchIndividualsResponseBuilderAssert hasNextPageToken(String nextPageToken) {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nextPageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualNextPageToken = actual.getNextPageToken();
    if (!Objects.areEqual(actualNextPageToken, nextPageToken)) {
      failWithMessage(assertjErrorMessage, actual, nextPageToken, actualNextPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder has individuals.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsResponse.Builder does not have individuals.
   */
  public GASearchIndividualsResponseBuilderAssert hasIndividuals() {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasIndividuals()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsResponse.Builder has individuals but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder does not have individuals.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsResponse.Builder has individuals.
   */
  public GASearchIndividualsResponseBuilderAssert doesNotHaveIndividuals() {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasIndividuals()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsResponse.Builder does not have individuals but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder has next page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsResponse.Builder does not have next page token.
   */
  public GASearchIndividualsResponseBuilderAssert hasNextPageToken() {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasNextPageToken()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsResponse.Builder has next page token but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsResponse.Builder does not have next page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsResponse.Builder has next page token.
   */
  public GASearchIndividualsResponseBuilderAssert doesNotHaveNextPageToken() {
    // check that actual GASearchIndividualsResponse.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasNextPageToken()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsResponse.Builder does not have next page token but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

}
