package org.ga4gh;

/**
 * {@link GASearchExperimentsRequest.Builder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchExperimentsRequestBuilderAssert extends AbstractAssert<GASearchExperimentsRequestBuilderAssert, GASearchExperimentsRequest.Builder> {

  /**
   * Creates a new <code>{@link GASearchExperimentsRequestBuilderAssert}</code> to make assertions on actual GASearchExperimentsRequest.Builder.
   * @param actual the GASearchExperimentsRequest.Builder we want to make assertions on.
   */
  public GASearchExperimentsRequestBuilderAssert(GASearchExperimentsRequest.Builder actual) {
    super(actual, GASearchExperimentsRequestBuilderAssert.class);
  }

  /**
   * An entry point for GASearchExperimentsRequestBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchExperimentsRequest.Builder)</code> and get specific assertion with code completion.
   * @param actual the GASearchExperimentsRequest.Builder we want to make assertions on.
   * @return a new <code>{@link GASearchExperimentsRequestBuilderAssert}</code>
   */
  public static GASearchExperimentsRequestBuilderAssert assertThat(GASearchExperimentsRequest.Builder actual) {
    return new GASearchExperimentsRequestBuilderAssert(actual);
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder's name is equal to the given one.
   * @param name the given name to compare the actual GASearchExperimentsRequest.Builder's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder's name is not equal to the given one.
   */
  public GASearchExperimentsRequestBuilderAssert hasName(String name) {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchExperimentsRequest.Builder's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder's pageSize is not equal to the given one.
   */
  public GASearchExperimentsRequestBuilderAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchExperimentsRequest.Builder's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder's pageToken is not equal to the given one.
   */
  public GASearchExperimentsRequestBuilderAssert hasPageToken(String pageToken) {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder has name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder does not have name.
   */
  public GASearchExperimentsRequestBuilderAssert hasName() {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchExperimentsRequest.Builder has name but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder does not have name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder has name.
   */
  public GASearchExperimentsRequestBuilderAssert doesNotHaveName() {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchExperimentsRequest.Builder does not have name but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder has page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder does not have page size.
   */
  public GASearchExperimentsRequestBuilderAssert hasPageSize() {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchExperimentsRequest.Builder has page size but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder does not have page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder has page size.
   */
  public GASearchExperimentsRequestBuilderAssert doesNotHavePageSize() {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchExperimentsRequest.Builder does not have page size but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder has page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder does not have page token.
   */
  public GASearchExperimentsRequestBuilderAssert hasPageToken() {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchExperimentsRequest.Builder has page token but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest.Builder does not have page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest.Builder has page token.
   */
  public GASearchExperimentsRequestBuilderAssert doesNotHavePageToken() {
    // check that actual GASearchExperimentsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchExperimentsRequest.Builder does not have page token but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

}
