package org.ga4gh;

import org.assertj.core.api.*;
import org.assertj.core.internal.*;
import org.assertj.core.util.*;

/**
 * {@link GASearchExperimentsResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchExperimentsResponseAssert extends AbstractAssert<GASearchExperimentsResponseAssert, GASearchExperimentsResponse> {

  /**
   * Creates a new <code>{@link GASearchExperimentsResponseAssert}</code> to make assertions on actual GASearchExperimentsResponse.
   * @param actual the GASearchExperimentsResponse we want to make assertions on.
   */
  public GASearchExperimentsResponseAssert(GASearchExperimentsResponse actual) {
    super(actual, GASearchExperimentsResponseAssert.class);
  }

  /**
   * An entry point for GASearchExperimentsResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchExperimentsResponse)</code> and get specific assertion with code completion.
   * @param actual the GASearchExperimentsResponse we want to make assertions on.
   * @return a new <code>{@link GASearchExperimentsResponseAssert}</code>
   */
  public static GASearchExperimentsResponseAssert assertThat(GASearchExperimentsResponse actual) {
    return new GASearchExperimentsResponseAssert(actual);
  }

  /**
   * Verifies that the actual GASearchExperimentsResponse's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchExperimentsResponse's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsResponse's classSchema is not equal to the given one.
   */
  public GASearchExperimentsResponseAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchExperimentsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsResponse's experiments contains the given GAExperiment elements.
   * @param experiments the given elements that should be contained in actual GASearchExperimentsResponse's experiments.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchExperimentsResponse's experiments does not contain all given GAExperiment elements.
   */
  public GASearchExperimentsResponseAssert hasExperiments(GAExperiment... experiments) {
    // check that actual GASearchExperimentsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAExperiment varargs is not null.
    if (experiments == null) failWithMessage("Expecting experiments parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getExperiments(), experiments);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsResponse's experiments contains <b>only<b> the given GAExperiment elements and nothing else in whatever order.
   * @param experiments the given elements that should be contained in actual GASearchExperimentsResponse's experiments.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchExperimentsResponse's experiments does not contain all given GAExperiment elements.
   */
  public GASearchExperimentsResponseAssert hasOnlyExperiments(GAExperiment... experiments) {
    // check that actual GASearchExperimentsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAExperiment varargs is not null.
    if (experiments == null) failWithMessage("Expecting experiments parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getExperiments(), experiments);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsResponse's experiments does not contain the given GAExperiment elements.
   *
   * @param experiments the given elements that should not be in actual GASearchExperimentsResponse's experiments.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchExperimentsResponse's experiments contains any given GAExperiment elements.
   */
  public GASearchExperimentsResponseAssert doesNotHaveExperiments(GAExperiment... experiments) {
    // check that actual GASearchExperimentsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAExperiment varargs is not null.
    if (experiments == null) failWithMessage("Expecting experiments parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getExperiments(), experiments);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsResponse has no experiments.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchExperimentsResponse's experiments is not empty.
   */
  public GASearchExperimentsResponseAssert hasNoExperiments() {
    // check that actual GASearchExperimentsResponse we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have experiments but had :\n  <%s>";
    
    // check
    if (actual.getExperiments().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getExperiments());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchExperimentsResponse's nextPageToken is equal to the given one.
   * @param nextPageToken the given nextPageToken to compare the actual GASearchExperimentsResponse's nextPageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsResponse's nextPageToken is not equal to the given one.
   */
  public GASearchExperimentsResponseAssert hasNextPageToken(String nextPageToken) {
    // check that actual GASearchExperimentsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nextPageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualNextPageToken = actual.getNextPageToken();
    if (!Objects.areEqual(actualNextPageToken, nextPageToken)) {
      failWithMessage(assertjErrorMessage, actual, nextPageToken, actualNextPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsResponse's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchExperimentsResponse's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsResponse's schema is not equal to the given one.
   */
  public GASearchExperimentsResponseAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchExperimentsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }



}
