package org.ga4gh;

/**
 * {@link GASearchIndividualsRequest.Builder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchIndividualsRequestBuilderAssert extends AbstractAssert<GASearchIndividualsRequestBuilderAssert, GASearchIndividualsRequest.Builder> {

  /**
   * Creates a new <code>{@link GASearchIndividualsRequestBuilderAssert}</code> to make assertions on actual GASearchIndividualsRequest.Builder.
   * @param actual the GASearchIndividualsRequest.Builder we want to make assertions on.
   */
  public GASearchIndividualsRequestBuilderAssert(GASearchIndividualsRequest.Builder actual) {
    super(actual, GASearchIndividualsRequestBuilderAssert.class);
  }

  /**
   * An entry point for GASearchIndividualsRequestBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchIndividualsRequest.Builder)</code> and get specific assertion with code completion.
   * @param actual the GASearchIndividualsRequest.Builder we want to make assertions on.
   * @return a new <code>{@link GASearchIndividualsRequestBuilderAssert}</code>
   */
  public static GASearchIndividualsRequestBuilderAssert assertThat(GASearchIndividualsRequest.Builder actual) {
    return new GASearchIndividualsRequestBuilderAssert(actual);
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder's groupIds contains the given String elements.
   * @param groupIds the given elements that should be contained in actual GASearchIndividualsRequest.Builder's groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest.Builder's groupIds does not contain all given String elements.
   */
  public GASearchIndividualsRequestBuilderAssert hasGroupIds(String... groupIds) {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (groupIds == null) failWithMessage("Expecting groupIds parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getGroupIds(), groupIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder's groupIds contains <b>only<b> the given String elements and nothing else in whatever order.
   * @param groupIds the given elements that should be contained in actual GASearchIndividualsRequest.Builder's groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest.Builder's groupIds does not contain all given String elements.
   */
  public GASearchIndividualsRequestBuilderAssert hasOnlyGroupIds(String... groupIds) {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (groupIds == null) failWithMessage("Expecting groupIds parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getGroupIds(), groupIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder's groupIds does not contain the given String elements.
   *
   * @param groupIds the given elements that should not be in actual GASearchIndividualsRequest.Builder's groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest.Builder's groupIds contains any given String elements.
   */
  public GASearchIndividualsRequestBuilderAssert doesNotHaveGroupIds(String... groupIds) {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (groupIds == null) failWithMessage("Expecting groupIds parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getGroupIds(), groupIds);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder has no groupIds.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchIndividualsRequest.Builder's groupIds is not empty.
   */
  public GASearchIndividualsRequestBuilderAssert hasNoGroupIds() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have groupIds but had :\n  <%s>";
    
    // check
    if (actual.getGroupIds().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getGroupIds());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder's name is equal to the given one.
   * @param name the given name to compare the actual GASearchIndividualsRequest.Builder's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder's name is not equal to the given one.
   */
  public GASearchIndividualsRequestBuilderAssert hasName(String name) {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchIndividualsRequest.Builder's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder's pageSize is not equal to the given one.
   */
  public GASearchIndividualsRequestBuilderAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchIndividualsRequest.Builder's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder's pageToken is not equal to the given one.
   */
  public GASearchIndividualsRequestBuilderAssert hasPageToken(String pageToken) {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder has group ids.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder does not have group ids.
   */
  public GASearchIndividualsRequestBuilderAssert hasGroupIds() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasGroupIds()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder has group ids but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder does not have group ids.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder has group ids.
   */
  public GASearchIndividualsRequestBuilderAssert doesNotHaveGroupIds() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasGroupIds()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder does not have group ids but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder has name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder does not have name.
   */
  public GASearchIndividualsRequestBuilderAssert hasName() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder has name but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder does not have name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder has name.
   */
  public GASearchIndividualsRequestBuilderAssert doesNotHaveName() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder does not have name but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder has page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder does not have page size.
   */
  public GASearchIndividualsRequestBuilderAssert hasPageSize() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder has page size but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder does not have page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder has page size.
   */
  public GASearchIndividualsRequestBuilderAssert doesNotHavePageSize() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder does not have page size but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder has page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder does not have page token.
   */
  public GASearchIndividualsRequestBuilderAssert hasPageToken() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder has page token but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchIndividualsRequest.Builder does not have page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchIndividualsRequest.Builder has page token.
   */
  public GASearchIndividualsRequestBuilderAssert doesNotHavePageToken() {
    // check that actual GASearchIndividualsRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchIndividualsRequest.Builder does not have page token but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

}
