package org.ga4gh;

/**
 * {@link GASearchAnalysesRequest.Builder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchAnalysesRequestBuilderAssert extends AbstractAssert<GASearchAnalysesRequestBuilderAssert, GASearchAnalysesRequest.Builder> {

  /**
   * Creates a new <code>{@link GASearchAnalysesRequestBuilderAssert}</code> to make assertions on actual GASearchAnalysesRequest.Builder.
   * @param actual the GASearchAnalysesRequest.Builder we want to make assertions on.
   */
  public GASearchAnalysesRequestBuilderAssert(GASearchAnalysesRequest.Builder actual) {
    super(actual, GASearchAnalysesRequestBuilderAssert.class);
  }

  /**
   * An entry point for GASearchAnalysesRequestBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchAnalysesRequest.Builder)</code> and get specific assertion with code completion.
   * @param actual the GASearchAnalysesRequest.Builder we want to make assertions on.
   * @return a new <code>{@link GASearchAnalysesRequestBuilderAssert}</code>
   */
  public static GASearchAnalysesRequestBuilderAssert assertThat(GASearchAnalysesRequest.Builder actual) {
    return new GASearchAnalysesRequestBuilderAssert(actual);
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder's name is equal to the given one.
   * @param name the given name to compare the actual GASearchAnalysesRequest.Builder's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder's name is not equal to the given one.
   */
  public GASearchAnalysesRequestBuilderAssert hasName(String name) {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchAnalysesRequest.Builder's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder's pageSize is not equal to the given one.
   */
  public GASearchAnalysesRequestBuilderAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchAnalysesRequest.Builder's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder's pageToken is not equal to the given one.
   */
  public GASearchAnalysesRequestBuilderAssert hasPageToken(String pageToken) {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder has name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder does not have name.
   */
  public GASearchAnalysesRequestBuilderAssert hasName() {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesRequest.Builder has name but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder does not have name.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder has name.
   */
  public GASearchAnalysesRequestBuilderAssert doesNotHaveName() {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasName()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesRequest.Builder does not have name but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder has page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder does not have page size.
   */
  public GASearchAnalysesRequestBuilderAssert hasPageSize() {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesRequest.Builder has page size but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder does not have page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder has page size.
   */
  public GASearchAnalysesRequestBuilderAssert doesNotHavePageSize() {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesRequest.Builder does not have page size but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder has page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder does not have page token.
   */
  public GASearchAnalysesRequestBuilderAssert hasPageToken() {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesRequest.Builder has page token but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesRequest.Builder does not have page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesRequest.Builder has page token.
   */
  public GASearchAnalysesRequestBuilderAssert doesNotHavePageToken() {
    // check that actual GASearchAnalysesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchAnalysesRequest.Builder does not have page token but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

}
