package org.ga4gh;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * {@link GASearchAnalysesResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchAnalysesResponseAssert extends AbstractAssert<GASearchAnalysesResponseAssert, GASearchAnalysesResponse> {

  /**
   * Creates a new <code>{@link GASearchAnalysesResponseAssert}</code> to make assertions on actual GASearchAnalysesResponse.
   * @param actual the GASearchAnalysesResponse we want to make assertions on.
   */
  public GASearchAnalysesResponseAssert(GASearchAnalysesResponse actual) {
    super(actual, GASearchAnalysesResponseAssert.class);
  }

  /**
   * An entry point for GASearchAnalysesResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchAnalysesResponse)</code> and get specific assertion with code completion.
   * @param actual the GASearchAnalysesResponse we want to make assertions on.
   * @return a new <code>{@link GASearchAnalysesResponseAssert}</code>
   */
  public static GASearchAnalysesResponseAssert assertThat(GASearchAnalysesResponse actual) {
    return new GASearchAnalysesResponseAssert(actual);
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse's analyses contains the given GAAnalysis elements.
   * @param analyses the given elements that should be contained in actual GASearchAnalysesResponse's analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse's analyses does not contain all given GAAnalysis elements.
   */
  public GASearchAnalysesResponseAssert hasAnalyses(GAAnalysis... analyses) {
    // check that actual GASearchAnalysesResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAAnalysis varargs is not null.
    if (analyses == null) failWithMessage("Expecting analyses parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getAnalyses(), analyses);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse's analyses contains <b>only<b> the given GAAnalysis elements and nothing else in whatever order.
   * @param analyses the given elements that should be contained in actual GASearchAnalysesResponse's analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse's analyses does not contain all given GAAnalysis elements.
   */
  public GASearchAnalysesResponseAssert hasOnlyAnalyses(GAAnalysis... analyses) {
    // check that actual GASearchAnalysesResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAAnalysis varargs is not null.
    if (analyses == null) failWithMessage("Expecting analyses parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getAnalyses(), analyses);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse's analyses does not contain the given GAAnalysis elements.
   *
   * @param analyses the given elements that should not be in actual GASearchAnalysesResponse's analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse's analyses contains any given GAAnalysis elements.
   */
  public GASearchAnalysesResponseAssert doesNotHaveAnalyses(GAAnalysis... analyses) {
    // check that actual GASearchAnalysesResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAAnalysis varargs is not null.
    if (analyses == null) failWithMessage("Expecting analyses parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getAnalyses(), analyses);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse has no analyses.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchAnalysesResponse's analyses is not empty.
   */
  public GASearchAnalysesResponseAssert hasNoAnalyses() {
    // check that actual GASearchAnalysesResponse we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have analyses but had :\n  <%s>";
    
    // check
    if (actual.getAnalyses().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getAnalyses());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchAnalysesResponse's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchAnalysesResponse's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse's classSchema is not equal to the given one.
   */
  public GASearchAnalysesResponseAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchAnalysesResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse's nextPageToken is equal to the given one.
   * @param nextPageToken the given nextPageToken to compare the actual GASearchAnalysesResponse's nextPageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse's nextPageToken is not equal to the given one.
   */
  public GASearchAnalysesResponseAssert hasNextPageToken(String nextPageToken) {
    // check that actual GASearchAnalysesResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nextPageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualNextPageToken = actual.getNextPageToken();
    if (!Objects.areEqual(actualNextPageToken, nextPageToken)) {
      failWithMessage(assertjErrorMessage, actual, nextPageToken, actualNextPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchAnalysesResponse's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchAnalysesResponse's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchAnalysesResponse's schema is not equal to the given one.
   */
  public GASearchAnalysesResponseAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchAnalysesResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }



}
