package org.ga4gh;

import org.assertj.core.api.*;
import org.assertj.core.util.*;

/**
 * {@link GASearchExperimentsRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchExperimentsRequestAssert extends AbstractAssert<GASearchExperimentsRequestAssert, GASearchExperimentsRequest> {

  /**
   * Creates a new <code>{@link GASearchExperimentsRequestAssert}</code> to make assertions on actual GASearchExperimentsRequest.
   * @param actual the GASearchExperimentsRequest we want to make assertions on.
   */
  public GASearchExperimentsRequestAssert(GASearchExperimentsRequest actual) {
    super(actual, GASearchExperimentsRequestAssert.class);
  }

  /**
   * An entry point for GASearchExperimentsRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchExperimentsRequest)</code> and get specific assertion with code completion.
   * @param actual the GASearchExperimentsRequest we want to make assertions on.
   * @return a new <code>{@link GASearchExperimentsRequestAssert}</code>
   */
  public static GASearchExperimentsRequestAssert assertThat(GASearchExperimentsRequest actual) {
    return new GASearchExperimentsRequestAssert(actual);
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchExperimentsRequest's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest's classSchema is not equal to the given one.
   */
  public GASearchExperimentsRequestAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchExperimentsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest's name is equal to the given one.
   * @param name the given name to compare the actual GASearchExperimentsRequest's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest's name is not equal to the given one.
   */
  public GASearchExperimentsRequestAssert hasName(String name) {
    // check that actual GASearchExperimentsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchExperimentsRequest's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest's pageSize is not equal to the given one.
   */
  public GASearchExperimentsRequestAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchExperimentsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchExperimentsRequest's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest's pageToken is not equal to the given one.
   */
  public GASearchExperimentsRequestAssert hasPageToken(String pageToken) {
    // check that actual GASearchExperimentsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchExperimentsRequest's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchExperimentsRequest's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchExperimentsRequest's schema is not equal to the given one.
   */
  public GASearchExperimentsRequestAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchExperimentsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }




}
